alias ls='ls --color=auto'
alias lsa='clear; ls -a; echo'
alias ..='cd ..'
alias clear='clear; clear'
alias python='python3'
alias py='python3'
alias go='clear;cd ~/Capstone; py user_interface_holden.py'
