alias ls='ls --color=auto'
alias lsa='clear; ls -a; echo'
alias lsl='ls -l'
alias ..='cd ..'
alias clear='clear; clear'
alias python='python3'
alias py='python3'
alias tracert='traceroute'
alias ipconfig='ifconfig'
